### ISSUE TITLE
WiFi HID emulator

### ISSUE THREAD

**Issue by mkeyno** [qlyoung/armory-keyboard#7]
hi , sorry to open a ticket for my question, but I have a question that may related to your field of repository and any possible hint really appreciated
Actually I interested to send game-pad data by WiFi bridge to my laptop, but generic joystick only use USB port, Is there a way to emulate "HID-compliant game controller" driver which listen to IP message instead of USB port
Tnx

**Comment by qlyoung** [comment]
Yes there is. If you own a USBArmory you can look for (or write) such an application using the same technologies the keyboard emulator uses. In fact if you're running Linux you can write such an emulator entirely in software without a USBArmory at all. If you're running Windows, you will need an Armory or similar device as emulating USB devices in software under Windows is essentially impossible last time I checked for various reasons, not least of which are the absurdly high requirements for driver signatures...

For IP support specifically, I would check out [USB/IP](http://usbip.sourceforge.net/). I believe Linux has native support for this via a kernel module iirc. Although again if you want to use this under Windows, the signed version has a bug that causes a kernel panic, and the patched version is not signed.

**Comment by mkeyno** [comment]
thanks @qlyoung  but I think adding another hardware is not very good idea because we already have WiFi link on every laptop, but before receiving your reply I was digging on the Windows Devices HID API on WDK (Window Driver Kit) sources but unfortunately there is no sample for HID over WiFi yet 
right now I'm trying to find a code to bind wifi link to the HID emulator . As I almost  prepare server side (ESP8266 with websocket server ) I look for code to establish websocket listener on emulator 
I might add, I found [ this site](http://maxjoypad.com/) that made similar software ,but unfortunately it is not opensource to modify it

**Comment by qlyoung** [comment]
Since it sounds like you're going with Windows - good luck. As I said, to my knowledge there is no way to emulate USB devices in software under Windows for the reasons I listed. Even if you develop a shim driver you still need to get it [signed](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-) to run under Windows. USB/IP drivers kernel panic on device detach. UDE was removed. I wish I knew a way. Please do let me know if you find one.
